[package]
name = "sir_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.12.0"
curl = "0.4.44"
reqwest = {version = "0.11.23", features = ['json']}
futures = "0.3.29"
tokio = {version = "1", features = ["full"]}
urlencoding = "2.1.3"
